CREATE TABLE Active_Connection (
	Timestamp TIMESTAMP NOT NULL,
	Src_IP VARCHAR(15) NOT NULL,
	Dst_IP VARCHAR(15) NOT NULL,
	Src_Port TINYINT NOT NULL,
	Dst_Port TINYINT NOT NULL,
	CONSTRAINT AC_PK PRIMARY KEY(Timestamp, Src_IP, Dst_IP, Src_Port, Dst_Port)
);

CREATE TABLE Average_Data_Volume (
	IP_A VARCHAR(15) NOT NULL,
	IP_B VARCHAR(15) NOT NULL,
	Payload_Sum INTEGER DEFAULT '0' NOT NULL,
	Payload_Count SMALLINT DEFAULT '0' NOT NULL,
	CONSTRAINT ADV_PK PRIMARY KEY(IP_A, IP_B)
);

CREATE TABLE IP_Connections (
	Dst_IP VARCHAR(15) NOT NULL,
	Dst_Port TINYINT NOT NULL,
	Src_IP VARCHAR(15) NOT NULL,
	CONSTRAINT IPC_PK PRIMARY KEY(Dst_IP, Dst_Port, Src_IP)
);

CREATE TABLE Syn_Fin_Ratio(
	Time_Range TIMESTAMP NOT NULL,
	Real_Time TIMESTAMP NOT NULL,
	Flag VARCHAR(1),
);

CREATE TABLE Packet(
	pk VARCHAR(50) NOT NULL,
	Src_IP VARCHAR(15) NOT NULL,
	Dst_IP VARCHAR(15) NOT NULL,
	Src_Port INTEGER NOT NULL,
	Dst_Port INTEGER NOT NULL,
	Payload VARCHAR NOT NULL,
	Time TIMESTAMP NOT NULL,
	Flag VARCHAR(1),
	Type VARCHAR(1),
	CONSTRAINT PACKET_PK PRIMARY KEY(pk)
	 	
);

CREATE TABLE Well_Known_Ports(
	Dst_IP VARCHAR(15) NOT NULL,
	Dst_Port INTEGER NOT NULL
);
